- hosts: "{{ _hosts }}"
  vars:
    httpd_pkg:
      - httpd
      - php
      - php-mysql
  tasks:
    - name: Install 
      yum:
        name: "{{ item }}"
        state: latest
      with_items:
        - "{{ httpd_pkg }}"
